package com.allegoria.admin.dom.enums;

//license-header java merge-point
//
//Attention: Generated code! Do not modify by hand!
//Generated by: TypeSafeEnumeration.vsl in andromda-java-cartridge.
//

/**
* 
*/
public enum ChoixDocumentOffice
 implements java.io.Serializable
{
 IBAN, //
 LOGO, //
 ETUDE, //
 DOCUMENT_1, //
 DOCUMENT_2, //
 DOCUMENT_3, //
 DOCUMENT_4, //
 DOCUMENT_5, //
 DOCUMENT_6, //
 DOCUMENT_7, //
 DOCUMENT_8, //
 DOCUMENT_9, //
 DOCUMENT_10; //


 /**
  * The default constructor allowing
  * super classes to access it.
  */
 private ChoixDocumentOffice()
 {
 }


	/**
  * Retrieves an instance of ChoixDocumentOffice from <code>its name</code>.
  *
  * @param name the name to create the ChoixDocumentOffice from.
  * @return The enumeration literal named after the 'name' argument
  */
 public static ChoixDocumentOffice fromString(String name)
 {
		return ChoixDocumentOffice.valueOf(name);
	}
	
	/**
	 * This method is necessary to comply with DaoBase implementation.
	 * @return The name of this literal.
	 */
	public Object getValue()
	{
		return this.name();
	}
}
