package com.allegoria.admin.dom.enums;

//license-header java merge-point
//
//Attention: Generated code! Do not modify by hand!
//Generated by: TypeSafeEnumeration.vsl in andromda-java-cartridge.
//


/**
* 
*/
public enum ChoixNatureMutation
 implements java.io.Serializable
{
 ACQUISITION, //
 ATTESTATION_DE_PROPRIETE, //
 DONATION, //
 DONATION_PARTAGE, //
 PARTAGE, //
 LICITATION, //
 LICITATION_INDIVISION_CESSE, //
 ECHANGE, //
 APPORT_EN_SOCIETE, //
 DISSOLUTION_DE_SOCIETE, //
 ATTRIBUTION, //
 ADJUDICATION, //
 ADJUDICATION_JUDICIAIRE, //
 ABANDON_USUFRUIT, //
 EXTINCTION_USUFRUIT, //
 JUGEMENT, //
 PRESCRIPTION_ACQUISITIVE, //
 ACTE_ADMINISTRATIF, //
 AUTRE_CAS; //


 /**
  * The default constructor allowing
  * super classes to access it.
  */
 private ChoixNatureMutation()
 {
 }


	/**
  * Retrieves an instance of ChoixNatureMutation from <code>its name</code>.
  *
  * @param name the name to create the ChoixNatureMutation from.
  * @return The enumeration literal named after the 'name' argument
  */
 public static ChoixNatureMutation fromString(String name)
 {
		return ChoixNatureMutation.valueOf(name);
	}
	
	/**
	 * This method is necessary to comply with DaoBase implementation.
	 * @return The name of this literal.
	 */
	public Object getValue()
	{
		return this.name();
	}
}
