// license-header java merge-point
//
// Attention: Generated code! Do not modify by hand!
// Generated by: TypeSafeEnumeration.vsl in andromda-java-cartridge.
//
package com.allegoria.admin.dom.enums;

/**
 * 
 */
public enum ChoixStatutOffice
    implements java.io.Serializable
{
    INDIVIDUEL, //
    SEL, //
    SCP, //
    SELAR, //
    SOCIETE_MOYEN; //


    /**
     * The default constructor allowing
     * super classes to access it.
     */
    private ChoixStatutOffice()
    {
    }


	/**
     * Retrieves an instance of ChoixStatutOffice from <code>its name</code>.
     *
     * @param name the name to create the ChoixStatutOffice from.
     * @return The enumeration literal named after the 'name' argument
     */
    public static ChoixStatutOffice fromString(String name)
    {
		return ChoixStatutOffice.valueOf(name);
	}
	
	/**
	 * This method is necessary to comply with DaoBase implementation.
	 * @return The name of this literal.
	 */
	public Object getValue()
	{
		return this.name();
	}
}
